[package]

name = "deuterium"
version = "0.0.1"
authors = ["Stanislav Panferov <fnight.m@gmail.com>"]

[[test]]
name = "tests"

[features]
default = ["postgres"]

[dependencies]
uuid = "*"
time = "*"

[dependencies.postgres]
varsion = "*"
optional = true