[package]

name = "deuterium"
version = "0.0.1"
authors = ["Stanislav Panferov <fnight.m@gmail.com>"]

[[test]]
name = "tests"

[features]
default = ["postgres"]
raw_expr = []

[dependencies.postgres]
optional = true
git = "https://github.com/sfackler/rust-postgres.git"